FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt yfinance

COPY simulator/ ./simulator/

CMD ["python", "-m", "simulator.simulator", "--mode", "batch", "--dataset-size", "medium"]
